Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-03, with the labels that each got.

#93 Make local testing easy
  .dockerignore
  CONTRIBUTING.md
  Dockerfile
  TESTING.md
  docker-compose.yml
Labels: dco-required

#73 TKGm azure hybrid RA addendum and deploy guide
  CONTRIBUTING.md
  automation/tko-on-azure-hybrid/0_keepers/.gitignore
  automation/tko-on-azure-hybrid/0_keepers/data.tf
  automation/tko-on-azure-hybrid/0_keepers/locals.tf
  automation/tko-on-azure-hybrid/0_keepers/main.tf
  automation/tko-on-azure-hybrid/0_keepers/output.tf
  automation/tko-on-azure-hybrid/0_keepers/provider.tf
  automation/tko-on-azure-hybrid/0_keepers/terraform.tfvars
  automation/tko-on-azure-hybrid/0_keepers/vars.tf
  automation/tko-on-azure-hybrid/0_keepers/vault.tf
  automation/tko-on-azure-hybrid/1_netsec/data.tf
  automation/tko-on-azure-hybrid/1_netsec/locals.tf
  automation/tko-on-azure-hybrid/1_netsec/main.tf
  automation/tko-on-azure-hybrid/1_netsec/output.tf
  automation/tko-on-azure-hybrid/1_netsec/provider.tftpl
  automation/tko-on-azure-hybrid/1_netsec/terraform.tfvars
  automation/tko-on-azure-hybrid/1_netsec/user-subnets.tf
  automation/tko-on-azure-hybrid/1_netsec/vars.tf
  automation/tko-on-azure-hybrid/1_netsec/vault.tf
  automation/tko-on-azure-hybrid/2_dns/cloud.yaml
  automation/tko-on-azure-hybrid/2_dns/data.tf
  automation/tko-on-azure-hybrid/2_dns/main.tf
  automation/tko-on-azure-hybrid/2_dns/output.tf
  automation/tko-on-azure-hybrid/2_dns/provider.tftpl
  automation/tko-on-azure-hybrid/2_dns/terraform.tfvars
  automation/tko-on-azure-hybrid/2_dns/vars.tf
  automation/tko-on-azure-hybrid/3_bootstrap/cloud.tftpl
  automation/tko-on-azure-hybrid/3_bootstrap/config.yaml.tftpl
  automation/tko-on-azure-hybrid/3_bootstrap/data.tftpl
  automation/tko-on-azure-hybrid/3_bootstrap/data_bootstrap.tf
  automation/tko-on-azure-hybrid/3_bootstrap/locals.tf
  automation/tko-on-azure-hybrid/3_bootstrap/main.tf
  automation/tko-on-azure-hybrid/3_bootstrap/output.tf
  automation/tko-on-azure-hybrid/3_bootstrap/part-handler.py.tftpl
  automation/tko-on-azure-hybrid/3_bootstrap/provider.tftpl
  automation/tko-on-azure-hybrid/3_bootstrap/terraform.tfvars
  automation/tko-on-azure-hybrid/3_bootstrap/vars.tf
  automation/tko-on-azure-hybrid/3_bootstrap/vault.tf
  automation/tko-on-azure-hybrid/modules/akv/main.tf
  automation/tko-on-azure-hybrid/modules/controlplane_subnet/locals.tf
  automation/tko-on-azure-hybrid/modules/controlplane_subnet/main.tf
  automation/tko-on-azure-hybrid/modules/controlplane_subnet/output.tf
  automation/tko-on-azure-hybrid/modules/controlplane_subnet/vars.tf
  automation/tko-on-azure-hybrid/modules/node_subnet/locals.tf
  automation/tko-on-azure-hybrid/modules/node_subnet/main.tf
  automation/tko-on-azure-hybrid/modules/node_subnet/output.tf
  automation/tko-on-azure-hybrid/modules/node_subnet/vars.tf
  automation/tko-on-azure-hybrid/modules/vm/main.tf
  automation/tko-on-azure-hybrid/modules/vnet/Get-TfObjFromAzure.ps1
  automation/tko-on-azure-hybrid/modules/vnet/log_analytics.tf
  automation/tko-on-azure-hybrid/modules/vnet/main.tf
  automation/tko-on-azure-hybrid/modules/vnet/output.tf
  automation/tko-on-azure-hybrid/modules/vnet/vars.tf
  automation/tko-on-azure-hybrid/readme.md
  src/reference-designs/img/tko-on-azure/tkgm-azure-hybrid.png
  src/reference-designs/tko-on-azure-hybrid.md
  wordlist.txt
Labels: cla-not-required, reference-design

#127 Tap architecture planning
  src/reference-designs/tap-architecture-planning.md
Labels: dco-required

#63 Created dedicated md file for TKO SaaS contents for RA
  src/reference-designs/img/tko-on-vmc-aws/image002.jpg
  src/reference-designs/img/tko-on-vmc-aws/image004.jpg
  src/reference-designs/img/tko-on-vmc-aws/image006.jpg
  src/reference-designs/img/tko-on-vmc-aws/image008.jpg
  src/reference-designs/img/tko-on-vmc-aws/image010.jpg
  src/reference-designs/img/tko-on-vmc-aws/image012.jpg
  src/reference-designs/img/tko-on-vmc-aws/image014.jpg
  src/reference-designs/img/tko-on-vmc-aws/image016.jpg
  src/reference-designs/img/tko-on-vmc-aws/image018.jpg
  src/reference-designs/img/tko-on-vmc-aws/image020.jpg
  src/reference-designs/img/tko-on-vmc-aws/image022.jpg
  src/reference-designs/img/tko-on-vmc-aws/image024.jpg
  src/reference-designs/img/tko-on-vmc-aws/image026.jpg
  src/reference-designs/img/tko-on-vmc-aws/image028.jpg
  src/reference-designs/img/tko-on-vmc-aws/image030.jpg
  src/reference-designs/img/tko-on-vmc-aws/image032.jpg
  src/reference-designs/img/tko-on-vmc-aws/image034.jpg
  src/reference-designs/img/tko-on-vmc-aws/image036.jpg
  src/reference-designs/img/tko-on-vmc-aws/image038.jpg
  src/reference-designs/img/tko-on-vsphere-nsx/image1.png
  src/reference-designs/img/tko-on-vsphere-nsx/image10.png
  src/reference-designs/img/tko-on-vsphere-nsx/image11.png
  src/reference-designs/img/tko-on-vsphere-nsx/image14.png
  src/reference-designs/img/tko-on-vsphere-nsx/image15.png
  src/reference-designs/img/tko-on-vsphere-nsx/image17.png
  src/reference-designs/img/tko-on-vsphere-nsx/image22.png
  src/reference-designs/img/tko-on-vsphere-nsx/image23.png
  src/reference-designs/img/tko-on-vsphere-nsx/image24.png
  src/reference-designs/img/tko-on-vsphere-nsx/image25.png
  src/reference-designs/img/tko-on-vsphere-nsx/image27.png
  src/reference-designs/img/tko-on-vsphere-nsx/image28.png
  src/reference-designs/img/tko-on-vsphere-nsx/image29.png
  src/reference-designs/img/tko-on-vsphere-nsx/image30.png
  src/reference-designs/img/tko-on-vsphere-nsx/image33.png
  src/reference-designs/img/tko-on-vsphere-nsx/image34.png
  src/reference-designs/img/tko-on-vsphere-nsx/image4.png
  src/reference-designs/img/tko-on-vsphere-nsx/image7.png
  src/reference-designs/img/tko-on-vsphere-nsx/image9.png
  src/reference-designs/img/tko-saas/TSM-App-Connectivity.png
  src/reference-designs/img/tko-saas/TSM-Architecture.png
  src/reference-designs/img/tko-saas/TSM-Global-Namespace.png
  src/reference-designs/img/tko-saas/TSM-Observability.png
  src/reference-designs/img/tko-saas/TSM-Resiliency.png
  src/reference-designs/tko-on-vmc-aws.md
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere.md
  src/reference-designs/tko-saas.md
  src/toc.md
Labels: cla-rejected, ready-for-ix-review
