Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-04, with the labels that each got.

#76 Tanzu Application Platform Deployment Guide
  src/deployment-guides/tap.md
Labels: cla-not-required, ready-for-ix-review

#119 Add TKO for vSphere and VDS Deployment Guide
  src/deployment-guides/img/tko-on-vsphere-vds/image1.png
  src/deployment-guides/img/tko-on-vsphere-vds/image11.png
  src/deployment-guides/img/tko-on-vsphere-vds/image14.png
  src/deployment-guides/img/tko-on-vsphere-vds/image16.png
  src/deployment-guides/img/tko-on-vsphere-vds/image17.png
  src/deployment-guides/img/tko-on-vsphere-vds/image18.png
  src/deployment-guides/img/tko-on-vsphere-vds/image19.png
  src/deployment-guides/img/tko-on-vsphere-vds/image20.png
  src/deployment-guides/img/tko-on-vsphere-vds/image21.png
  src/deployment-guides/img/tko-on-vsphere-vds/image22.png
  src/deployment-guides/img/tko-on-vsphere-vds/image23.png
  src/deployment-guides/img/tko-on-vsphere-vds/image25.png
  src/deployment-guides/img/tko-on-vsphere-vds/image27.png
  src/deployment-guides/img/tko-on-vsphere-vds/image29.png
  src/deployment-guides/img/tko-on-vsphere-vds/image31.png
  src/deployment-guides/img/tko-on-vsphere-vds/image32.png
  src/deployment-guides/img/tko-on-vsphere-vds/image33.png
  src/deployment-guides/img/tko-on-vsphere-vds/image35.png
  src/deployment-guides/img/tko-on-vsphere-vds/image36.png
  src/deployment-guides/img/tko-on-vsphere-vds/image37.png
  src/deployment-guides/img/tko-on-vsphere-vds/image38.png
  src/deployment-guides/img/tko-on-vsphere-vds/image4.png
  src/deployment-guides/img/tko-on-vsphere-vds/image41.png
  src/deployment-guides/img/tko-on-vsphere-vds/image43.png
  src/deployment-guides/img/tko-on-vsphere-vds/image44.png
  src/deployment-guides/img/tko-on-vsphere-vds/image45.png
  src/deployment-guides/img/tko-on-vsphere-vds/image46.png
  src/deployment-guides/img/tko-on-vsphere-vds/image47.png
  src/deployment-guides/img/tko-on-vsphere-vds/image49.png
  src/deployment-guides/img/tko-on-vsphere-vds/image5.png
  src/deployment-guides/img/tko-on-vsphere-vds/image50.png
  src/deployment-guides/img/tko-on-vsphere-vds/image51.png
  src/deployment-guides/img/tko-on-vsphere-vds/image53.png
  src/deployment-guides/img/tko-on-vsphere-vds/image54.png
  src/deployment-guides/img/tko-on-vsphere-vds/image55.png
  src/deployment-guides/img/tko-on-vsphere-vds/image58.png
  src/deployment-guides/img/tko-on-vsphere-vds/image59.png
  src/deployment-guides/img/tko-on-vsphere-vds/image64.png
  src/deployment-guides/img/tko-on-vsphere-vds/image66.png
  src/deployment-guides/img/tko-on-vsphere-vds/image68.png
  src/deployment-guides/img/tko-on-vsphere-vds/image69.png
  src/deployment-guides/img/tko-on-vsphere-vds/image71.png
  src/deployment-guides/img/tko-on-vsphere-vds/image72.png
  src/deployment-guides/img/tko-on-vsphere-vds/image74.png
  src/deployment-guides/img/tko-on-vsphere-vds/image75.png
  src/deployment-guides/img/tko-on-vsphere-vds/image79.png
  src/deployment-guides/img/tko-on-vsphere-vds/image8.png
  src/deployment-guides/img/tko-on-vsphere-vds/image80.png
  src/deployment-guides/img/tko-on-vsphere-vds/image81.png
  src/deployment-guides/img/tko-on-vsphere-vds/image82.png
  src/deployment-guides/img/tko-on-vsphere-vds/image84.png
  src/deployment-guides/img/tko-on-vsphere-vds/image86.png
  src/deployment-guides/img/tko-on-vsphere-vds/image87.png
  src/deployment-guides/img/tko-on-vsphere-vds/image90.png
  src/deployment-guides/img/tko-on-vsphere-vds/image91.png
  src/deployment-guides/img/tko-on-vsphere-vds/image92.png
  src/deployment-guides/img/tko-on-vsphere-vds/image93.png
  src/deployment-guides/img/tko-on-vsphere-vds/image94.png
  src/deployment-guides/img/tko-on-vsphere-vds/image95.png
  src/deployment-guides/tko-on-vsphere-vds.md
Labels: ready-for-ix-review

#144 Fix AWS jumpbox instructions
  src/deployment-guides/tko-aws.md
Labels: dco-required

#96 TKO-AWS 1.5.1 RA and DG changes
  src/deployment-guides/tko-aws.md
  src/deployment-guides/tko-saas-services.md
  src/reference-designs/img/tko-on-aws/tmc-register-management-cluster.jpg
  src/reference-designs/index.md
  src/reference-designs/tko-on-aws.md
Labels: cla-not-required, do-not-merge, ix-review-done

#129 Clarify harbor support statement
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
Labels: do-not-merge, ix-review-done
