Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-10, with the labels that each got.

#278 TKO 1.6 changes for landing page
  src/deployment-guides/tko-on-vsphere.md
  src/reference-designs/index.md
  src/toc.md
Labels: ready-to-merge

#280 tko160-nsx-ra
  src/reference-designs/img/tko-on-vsphere-nsx/tko-on-vsphere-nsxt-3.png
  src/reference-designs/img/tko-on-vsphere-nsx/tko-on-vsphere-nsxt-5.png
  src/reference-designs/img/tko-on-vsphere-nsx/tko-on-vsphere-nsxt-8.png
  src/reference-designs/tko-on-vsphere-nsx.md
Labels: ix-review-done

#282 Tko vmc aws 160
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws04.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws07.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws08.png
  src/reference-designs/tko-on-vmc-aws.md
Labels: ix-review-done, ready-to-merge

#291 Updated TKO 1.6 Deployment on AWS
  src/deployment-guides/tko-aws.md
Labels: ix-review-done, ready-to-merge

#290 TAP 1.3 Reference design update
  src/reference-designs/tap-architecture-planning.md
  wordlist.txt
Labels: ix-review-done, ready-to-merge

#297 introduced new enhancements in the doc
  src/reference-designs/tko-on-vsphere-nsx.md
Labels: dco-required, ix-review-done, ready-to-merge
