Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-07, with the labels that each got.

#228 Add text/link to the Observability custom dashboard topic
  src/deployment-guides/tko-saas-services.md
  src/reference-designs/tko-on-aws.md
  src/reference-designs/tko-on-azure.md
  src/reference-designs/tko-on-vmc-aws.md
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
  src/reference-designs/tko-saas.md
Labels: ix-review-done

#168 Tanzu Edge Solutions Architecture - initial commit
  src/reference-designs/img/tkg-edge/0547aae877598d9975f066451cb5b268.png
  src/reference-designs/img/tkg-edge/464ec91366a4b9ec9273ddb6b0c87804.png
  src/reference-designs/img/tkg-edge/559bfe3fa044f89dab66d033ee2168cf.png
  src/reference-designs/img/tkg-edge/91aa78cae6af4261e49171516d5cecb9.png
  src/reference-designs/img/tkg-edge/a93e92ad27bee927a258c5447a3ed78d.png
  src/reference-designs/img/tkg-edge/b24ac18e57b053174782c87492b3644d.png
  src/reference-designs/img/tkg-edge/b7fb5735e266dfaca19d1c5c45e64a3e.png
  src/reference-designs/img/tkg-edge/ce29c1e20bf0ecc1ffe2dfdc658cb585.png
  src/reference-designs/img/tkg-edge/e091590baba38bf13203c4166893699c.png
  src/reference-designs/img/tkg-edge/f312de8ea37cad334af63d608a37f3d6.png
  src/reference-designs/img/tkg-edge/f3a9b5e3df9d8c442b112da8fd660613.png
  src/reference-designs/img/tkg-edge/tkg-edge-dc-fleet.drawio.png
  src/reference-designs/img/tkg-edge/tkg-edge-harbor.drawio.png
  src/reference-designs/img/tkg-edge/tkg-edge-hub-spoke.drawio.png
  src/reference-designs/img/tkg-edge/tkg-edge-hybrid.drawio.png
  src/reference-designs/img/tkg-edge/tko-edge-networking.drawio.png
  src/reference-designs/index.md
  src/reference-designs/tkg-edge.md
  wordlist.txt
Labels: dco-required, tech-review-done, ix-provided-review

#230 changes to address git issue#216
  src/reference-designs/tko-on-vsphere-with-tanzu.md
Labels: ix-review-done

#233 Delete toc-original.md, which is a copy of toc.md
  src/toc-orginal.md
Labels: ix-review-done

#234 Updated graphics for PR 158
  src/reference-designs/img/tko-on-vsphere/images-monitoring-stack.png
  src/reference-designs/img/tko-on-vsphere/tko-on-vsphere-vds-2.png
  src/reference-designs/img/tko-on-vsphere/tko-on-vsphere-vds-3.png
Labels: ix-review-done

#231 Tanzu Application Platform Deployment Guide updated for V 1.1
  src/deployment-guides/tap.md
  wordlist.txt
Labels: ix-review-done

#238 Publish2 tap 1 1
  src/deployment-guides/tap.md
  src/reference-designs/index-tap.md
  src/reference-designs/tap-architecture-planning.md
  src/toc-tap.md
Labels: ix-review-done

#226 Revert harbor section to correct mistake
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu-nsxt.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
Labels: ix-provided-review
