Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-06, with the labels that each got.

#201 typo in link description to deployment guide
  src/reference-designs/tko-on-vsphere.md
Labels: dco-required

#210 Publish 1 5
  src/deployment-guides/tko-aws.md
  src/deployment-guides/tko-on-azure.md
  src/reference-designs/index.md
  src/reference-designs/tko-on-azure.md
  src/toc.md
Labels: ix-review-done

#187 adding tko-vwt-ra 2.0 doc
  src/reference-designs/img/tko-on-vsphere-with-tanzu/TKO-VWT-Reference-Design.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image1.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image11.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image12.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image13.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image14.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image15.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image16.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image17.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image19.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image20.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image21.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image22.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image23.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image24.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image3.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image5.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image6.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image7.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/image8.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt01.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt02.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt03.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt04.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt05.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt06.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt07.jpeg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt08.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt09.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt10.jpg
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt12.png
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  wordlist.txt
Labels: ix-review-done

#188 adding tko-saas-ra 2.0 doc
  src/reference-designs/img/tko-saas/tko-observability01.png
  src/reference-designs/img/tko-saas/tko-observability02.png
  src/reference-designs/img/tko-saas/tko-observability03.png
  src/reference-designs/img/tko-saas/tko-observability04.png
  src/reference-designs/img/tko-saas/tko-observability05.png
  src/reference-designs/img/tko-saas/tko-observability06.png
  src/reference-designs/img/tko-saas/tko-observability07.png
  src/reference-designs/img/tko-saas/tko-observability08.png
  src/reference-designs/img/tko-saas/tko-observability09.png
  src/reference-designs/img/tko-saas/tko-observability10.png
  src/reference-designs/img/tko-saas/tko-observability11.png
  src/reference-designs/img/tko-saas/tko-observability12.png
  src/reference-designs/img/tko-saas/tko-observability13.png
  src/reference-designs/img/tko-saas/tko-observability14.png
  src/reference-designs/img/tko-saas/tko-observability15.png
  src/reference-designs/img/tko-saas/tko-observability16.png
  src/reference-designs/img/tko-saas/tko-observability17.png
  src/reference-designs/img/tko-saas/tko-observability18.png
  src/reference-designs/img/tko-saas/tko-observability19.png
  src/reference-designs/tko-saas.md
  wordlist.txt
Labels: dco-required, ix-review-done

#190 adding tanzu-packages deploy guide
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs01.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs02.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs03.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs04.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs05.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs06.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs07.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs08.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs09.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs10.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs11.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs12.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs13.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs14.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs15.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs16.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs17.png
  src/deployment-guides/tkg-package-install.md
  wordlist.txt
Labels: dco-required, ix-review-done

#193 Adding tko-saas-deploy-guide 2.0
  src/deployment-guides/img/tko-saas-services/TKGS-TSM01.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM02.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM05.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM07.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM08.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM09.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM10.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM11.jpg
  src/deployment-guides/img/tko-saas-services/TKGS-TSM12.jpg
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster01.png
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster02.png
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster03.png
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster04.png
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster05.png
  src/deployment-guides/img/tko-saas-services/attach-workload-cluster06.png
  src/deployment-guides/img/tko-saas-services/image65.png
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas01.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas02.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas03.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas04.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas05.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas06-1.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas06.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas07.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas08.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas09.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas10.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas11.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas12.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas13.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas14.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas15.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas16.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas17.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas18.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas19.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas20.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas21.jpg
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas22.jpg
  src/deployment-guides/img/tko-saas-services/tmc-proxy-configuration01.png
  src/deployment-guides/img/tko-saas-services/tmc-proxy-configuration02.png
  src/deployment-guides/img/tko-saas-services/tmc-proxy-configuration03.png
  src/deployment-guides/tko-saas-services.md
  wordlist.txt
Labels: dco-required, ix-review-done

#207 Update some azure deployment instructions for 1.5
  src/deployment-guides/tko-on-azure.md
Labels: ix-review-done

#185 Adding data protection 2.0 RA
  src/reference-designs/tko-data-protection.md
  wordlist.txt
Labels: ix-review-done, tech-review-in-progress

#213 Fixed typos in tko-on-vsphere-vds
  src/deployment-guides/tko-on-vsphere-vds.md
Labels: dco-required

#160 Tanzu Reference Architecture/Deployment guide for Pinniped Integration
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-1.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-2.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-3.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-4.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-5.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-6.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-7.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-8.png
  src/deployment-guides/img/pinniped-with-tkg/01-pinniped-9.png
  src/deployment-guides/pinniped-with-tkg.md
  src/reference-designs/img/pinniped-with-tkg/1-pinniped-1.png
  src/reference-designs/pinniped-with-tkg.md
Labels: dco-required, ix-review-done

#218 adding tko-vmc-aws ra
  src/reference-designs/img/tko-on-vmc-aws/RefTanzuVMCAWS.png
  src/reference-designs/img/tko-on-vmc-aws/contourkubernetesingress.png
  src/reference-designs/img/tko-on-vmc-aws/multicluster.png
  src/reference-designs/img/tko-on-vmc-aws/singlecluster.png
  src/reference-designs/img/tko-on-vmc-aws/tkgworkloadnetwork.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws01.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws02.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws03.jpg
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws04.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws05.png
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws06.png
  src/reference-designs/img/tko-on-vmc-aws/vmcAwsContainerReg.png
  src/reference-designs/img/tko-on-vmc-aws/vmcAwsNsxALB.png
  src/reference-designs/img/tko-on-vmc-aws/vmcAwsSDDC.png
  src/reference-designs/img/tko-on-vmc-aws/vmcAwsStorage.png
  src/reference-designs/tko-on-vmc-aws.md
Labels: dco-required, ix-review-done

#208 vyatta: Add `govc` commands
  src/partials/vyatta.md
Labels: tech-review-in-progress

#209 Update reference architecture for Tanzu Application Platform 1.1
  src/deployment-guides/tko-on-azure.md
  src/reference-designs/tap-architecture-planning.md
Labels: ix-review-done, tech-review-done

#220 Update graphic to VMware standards
  src/reference-designs/img/tko-on-aws/tmc-global-policy-control-plane.png
Labels: ix-review-done

#221 Update picture to VMware standards
  src/reference-designs/img/pinniped-with-tkg/1-pinniped-1.png
Labels: ix-review-done

#203 add tkgs design
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image10.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image11.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image12.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image13.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image14.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image15.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image16.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image17.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image18.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image19.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image2.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image20.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image21.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image22.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image23.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image24.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image25.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image26.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image27.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image28.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image29.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image30.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image31.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image5.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image8.png
  src/reference-designs/img/tko-on-vsphere-with-tanzu-nsxt/image9.png
  src/reference-designs/tko-on-vsphere-with-tanzu-nsxt.md
  wordlist.txt
Labels: ix-review-done, tech-review-done

#224 TKO-NSX-T-1.5
  src/deployment-guides/img/tko-on-vsphere-nsxt/70-ss-8.png
  src/deployment-guides/tko-on-vsphere-nsxt.md
  src/reference-designs/img/tko-on-vsphere-nsx/TKO-Ref-Arch.jpg
  src/reference-designs/img/tko-on-vsphere-nsx/images-monitoring-stack.png
  src/reference-designs/tko-on-vsphere-nsx.md
  wordlist.txt
Labels: ix-review-done

#211 Adding customized dashboards of Tanzu Observability.
  automation/tko-to-customized-dashboards-json-scripts/kubernetesdeploymentdeamonset.json
  automation/tko-to-customized-dashboards-json-scripts/kubernetesresouce.json
  automation/tko-to-customized-dashboards-json-scripts/tkocustomizedsummary.json
  automation/tko-to-customized-dashboards-json-scripts/tkokuberneteshealthcheck.json
  automation/tko-to-customized-dashboards-json-scripts/tkokubernetesresourceutilization.json
  automation/tko-to-customized-dashboards-json-scripts/tkonetworkkubernetes.json
  src/deployment-guides/img/tko-to-customized-dashboards/cluster-health.png
  src/deployment-guides/img/tko-to-customized-dashboards/cluster-overview.png
  src/deployment-guides/img/tko-to-customized-dashboards/cluster-resource.png
  src/deployment-guides/img/tko-to-customized-dashboards/cluster-resources-kubernetes.png
  src/deployment-guides/img/tko-to-customized-dashboards/container-cpu-daemonset.png
  src/deployment-guides/img/tko-to-customized-dashboards/container-memory-daemonset.png
  src/deployment-guides/img/tko-to-customized-dashboards/containers-resource-overview.png
  src/deployment-guides/img/tko-to-customized-dashboards/kubernetes-network.png
  src/deployment-guides/img/tko-to-customized-dashboards/memory-cpu-kubernetes-resources.png
  src/deployment-guides/img/tko-to-customized-dashboards/namespace-overview.png
  src/deployment-guides/img/tko-to-customized-dashboards/node-resources-overview.png
  src/deployment-guides/img/tko-to-customized-dashboards/pod-overview.png
  src/deployment-guides/img/tko-to-customized-dashboards/terminatedpod-daemonset.png
  src/deployment-guides/img/tko-to-customized-dashboards/tko-summary-vsphere.png
  src/deployment-guides/tko-saas-services.md
  src/deployment-guides/tko-to-customized-dashboard.md
Labels: ix-review-done, tech-review-done

#225 TKO 1.5 publish 3
  src/deployment-guides/tko-in-vmc-aws.md
  src/deployment-guides/tko-on-vsphere-vds.md
  src/reference-designs/index.md
  src/reference-designs/tko-on-azure.md
  src/reference-designs/tko-on-vmc-aws.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
Labels: ix-review-done

#227 Tko 1 5 publish 4
  src/deployment-guides/tko-on-vsphere-nsxt.md
  src/deployment-guides/tko-on-vsphere-vds.md
  src/deployment-guides/tko-to-customized-dashboard.md
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
  src/toc.md
Labels: ix-review-done
