Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2022-08, with the labels that each got.

#240 Fix broken links
  src/reference-designs/tko-on-aws-airgap.md
  src/reference-designs/tko-on-aws.md
  src/reference-designs/tko-on-vsphere-with-tanzu-nsxt.md
Labels: ix-review-done

#196 Adding tkg-vsphere-vds-airgap RA doc
  src/reference-designs/img/vsphere-vds-airgap/ALB-Ingress.png
  src/reference-designs/img/vsphere-vds-airgap/Cluster-Compute-Utilization.png
  src/reference-designs/img/vsphere-vds-airgap/K8-API-Server.png
  src/reference-designs/img/vsphere-vds-airgap/Namepsace-Pods-Compute-Utilization.png
  src/reference-designs/img/vsphere-vds-airgap/Namepsace-Pods-Network-Utilization.png
  src/reference-designs/img/vsphere-vds-airgap/TKG-Storage.png
  src/reference-designs/img/vsphere-vds-airgap/network-architecture.jpg
  src/reference-designs/img/vsphere-vds-airgap/tkg-monitoring-stack.png
  src/reference-designs/vsphere-vds-airgap.md
  wordlist.txt
Labels: dco-required, ix-review-done

#177 171 tanzu service mesh workload cluster sizing
  src/deployment-guides/img/tko-saas-services/tko-deploy-saas23.png
  src/deployment-guides/tko-saas-services.md
Labels: ix-review-done, tech-review-done

#214 TKG on NSX-T in Airgap Environment RA
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap01.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap02.jpg
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap03.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap04.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap05.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap06.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap07.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap08.png
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap09.png
  src/reference-designs/tkg-nsxt-airgap-ra.md
  wordlist.txt
Labels: dco-required, ix-review-done

#222 Resolving issue 172 by placing a note on TSM onboarding regarding use…
  src/deployment-guides/tko-saas-services.md
Labels: ix-provided-review

#239 Publish air gap 1 0
  src/deployment-guides/tko-aws-airgap.md
  src/reference-designs/index-air-gap.md
  src/reference-designs/tko-on-aws-airgap.md
  src/toc-air-gap.md
Labels: ix-review-done

#251 updated subnet cidr and prometheus image
  src/reference-designs/tkg-nsxt-airgap-ra.md
Labels: ix-review-done

#252 Add Service Installer blurb
  src/deployment-guides/tko-aws.md
  src/deployment-guides/tko-in-vmc-aws.md
  src/deployment-guides/tko-on-vsphere-nsxt.md
  src/deployment-guides/tko-on-vsphere-vds.md
  src/deployment-guides/tko-on-vsphere-with-tanzu.md
Labels: ix-review-done

#247 Added note about using cluster.local for serviceDomain. Added info ab…
  src/deployment-guides/tap.md
Labels: ix-review-done

#255 fixed git issue 172
  src/deployment-guides/tko-saas-services.md
Labels: ix-review-done
