Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2023-01, with the labels that each got.

#306 Updated RA
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws02.png
  src/reference-designs/tko-on-vmc-aws.md
Labels: ix-review-done, ready-to-merge

#308 updated deployment guide
  src/deployment-guides/img/tko-in-vmc-aws/deploy-tko-vmc-22.JPG
  src/deployment-guides/img/tko-in-vmc-aws/deploy-tko-vmc-23.JPG
  src/deployment-guides/img/tko-in-vmc-aws/deploy-tko-vmc-40.JPG
  src/deployment-guides/img/tko-in-vmc-aws/deploy-tko-vmc-42.JPG
  src/deployment-guides/tko-in-vmc-aws.md
Labels: ix-review-done, ready-to-merge

#309 RA graphic fix
  src/reference-designs/img/index/tkgm-diagram.png
Labels: ready-to-merge

#312 IX changes for TKO 1.6, TAP 1.3, and airgapped 1.6 RA docs
  src/deployment-guides/tko-aws-airgap.md
  src/deployment-guides/tko-in-vmc-aws.md
  src/deployment-guides/tko-on-vsphere-nsxt.md
  src/deployment-guides/tko-on-vsphere.md
  src/reference-designs/img/tap-architecture-planning/overview.jpg
  src/reference-designs/index-air-gap.md
  src/reference-designs/index-tap.md
  src/reference-designs/tap-architecture-planning.md
  src/reference-designs/tko-on-vmc-aws.md
  src/reference-designs/tko-on-vsphere.md
  src/tko-vsphere-section.md
  src/toc-air-gap.md
  src/toc-tap.md
  src/toc.md
Labels: ready-to-merge

#307 TAP 1.3 RA enhancement for inner loop - phase 2
  src/reference-designs/img/tap-architecture-planning/accelerator-arch.jpg
  src/reference-designs/img/tap-architecture-planning/api-auto-regis-workflow.jpg
  src/reference-designs/img/tap-architecture-planning/appliveview-arch.jpg
  src/reference-designs/img/tap-architecture-planning/appsso-arch.jpg
  src/reference-designs/img/tap-architecture-planning/scst-arch.jpg
  src/reference-designs/tap-architecture-dev-components.md
  src/reference-designs/tap-architecture-planning.md
  wordlist.txt
Labels: dco-required, ix-review-done, ready-to-merge

#314 TAP 1.4 RA update
  src/reference-designs/index-tap.md
  src/reference-designs/tap-architecture-dev-components.md
  src/reference-designs/tap-architecture-planning.md
  src/toc-tap.md
Labels: ix-review-done, ready-to-merge
