Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2023-03, with the labels that each got.

#324 vSphere with tanzu RA 2.1.0
  src/reference-designs/img/tko-on-vsphere-with-tanzu/tko-vwt06.png
  src/reference-designs/tkg-nsxt-airgap-ra.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
Labels: ix-review-done

#316 Updated NSX-t RA with TKG 2.1.0
  src/reference-designs/img/tko-on-vsphere-nsx/tko-on-vsphere-nsxt-2.jpg
  src/reference-designs/tko-on-vsphere-nsx.md
Labels: ix-review-done

#328 TKG 2.1.0 | Package Deployment
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs01.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs02.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs03.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs04.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs05.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs06.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs07.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs08.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs09.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs10.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs11.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs12.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs13.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs14.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs15.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs16.png
  src/deployment-guides/img/tanzu-pkgs/tanzu-pkgs17.png
  src/deployment-guides/tkg-package-install.md
Labels: ix-review-done

#320 TKO VMC_ON_AWS_RA
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws03.jpg
  src/reference-designs/img/tko-on-vmc-aws/tko-vmc-aws07.png
  src/reference-designs/tko-on-vmc-aws.md
Labels: ix-review-done, ready-to-merge

#336 New_VDS_AirGap_RA
  src/reference-designs/img/vsphere-vds-airgap/ALB-Ingress.png
  src/reference-designs/img/vsphere-vds-airgap/network-architecture.jpg
  src/reference-designs/img/vsphere-vds-airgap/tkg-monitoring-stack.png
  src/reference-designs/tkg-vsphere-vds-airgap.md
Labels: ix-review-done, ready-to-merge

#341 VDS_AirGAP_DG
  src/deployment-guides/tkg-vsphere-vds-airgap.md
Labels: ix-review-done, ready-to-merge

#318 Updated TKO NSX-t Airgap RA with TKG 2.1.0
  src/reference-designs/img/tkg-nsxt-airgap/tkg-nsxt-airgap01.png
  src/reference-designs/tkg-nsxt-airgap-ra.md
Labels: ix-review-done, ix-provided-review
