Repository vmware-tanzu-labs/tanzu-validated-solutions, pull requests merged in 2023-07, with the labels that each got.

#370 TKO NSX RA for Multi VIP Network
  src/reference-designs/img/tko-on-vsphere-nsx/tko-on-vsphere-nsxt-2.png
  src/reference-designs/tko-on-vsphere-nsx.md
Labels: ix-review-done, ready-to-merge

#384 changed the toc to 2.1
  src/toc.md
Labels: ix-review-done

#385 Updated toc from 2.3 to 2.1
  src/reference-designs/tko-on-vsphere-with-tanzu-multi-az-nsx.md
  src/toc.md
Labels: ix-review-done

#380 committing seo changes for the RA docs
  src/deployment-guides/pinniped-with-tkg.md
  src/deployment-guides/tap.md
  src/deployment-guides/tkg-nsxt-airgap.md
  src/deployment-guides/tkg-package-install.md
  src/deployment-guides/tkg-vsphere-vds-airgap.md
  src/deployment-guides/tko-aws-airgap.md
  src/deployment-guides/tko-aws.md
  src/deployment-guides/tko-in-vmc-aws.md
  src/deployment-guides/tko-on-azure.md
  src/deployment-guides/tko-on-vsphere-nsxt.md
  src/deployment-guides/tko-on-vsphere-with-tanzu.md
  src/deployment-guides/tko-on-vsphere.md
  src/deployment-guides/tko-saas-services.md
  src/deployment-guides/tko-to-customized-dashboard.md
  src/reference-designs/index-air-gap.md
  src/reference-designs/index-edge.md
  src/reference-designs/index-tap.md
  src/reference-designs/index.md
  src/reference-designs/pinniped-with-tkg.md
  src/reference-designs/tap-architecture-dev-components.md
  src/reference-designs/tap-architecture-planning.md
  src/reference-designs/tap-networking.md
  src/reference-designs/tkg-nsxt-airgap-ra.md
  src/reference-designs/tkg-vsphere-vds-airgap.md
  src/reference-designs/tko-data-protection.md
  src/reference-designs/tko-on-aws-airgap.md
  src/reference-designs/tko-on-aws.md
  src/reference-designs/tko-on-azure-hybrid.md
  src/reference-designs/tko-on-azure.md
  src/reference-designs/tko-on-vmc-aws.md
  src/reference-designs/tko-on-vsphere-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu-multi-az-nsx.md
  src/reference-designs/tko-on-vsphere-with-tanzu-multi-az.md
  src/reference-designs/tko-on-vsphere-with-tanzu-nsxt.md
  src/reference-designs/tko-on-vsphere-with-tanzu.md
  src/reference-designs/tko-on-vsphere.md
  src/reference-designs/tko-saas.md
  src/tko-cloud-section.md
  src/tko-vsphere-section.md
  src/tko-vsphere-with-tanzu-section.md
  src/toc-air-gap.md
Labels: dco-required

#391 Tko for vpshere with nsx airgap ra update
  src/reference-designs/tkg-nsxt-airgap-ra.md
Labels: ix-review-done

#390 Tko for vsphere airgap ra update
  src/reference-designs/tkg-vsphere-vds-airgap.md
Labels: ix-review-done

#389 Tko for vmc on aws ra update
  src/reference-designs/tko-on-vmc-aws.md
Labels: ix-review-done

#388 Tko for vpshere with tanzu ra update
  src/reference-designs/tko-on-vsphere-with-tanzu.md
Labels: ix-review-done

#387 Tko for vsphere with nsx ra update
  src/reference-designs/tko-on-vsphere-nsx.md
Labels: ix-review-done

#386 Updated logging section and removed reference of helm
  src/reference-designs/tko-on-vsphere.md
Labels: ix-review-done
